import js from '@eslint/js';
import nextPlugin from '@next/eslint-plugin-next';
import reactHooks from 'eslint-plugin-react-hooks';
import globals from 'globals';
import tseslint from 'typescript-eslint';

/**
 * One flat config for the whole workspace.
 *
 * Each package runs `eslint src` from its own directory; ESLint walks up to this file, so the
 * rules that protect the architecture — no floating promises, no `any` leaking across a boundary —
 * are the same everywhere instead of drifting per package.
 */
export default tseslint.config(
  {
    ignores: [
      '**/dist/**',
      '**/.next/**',
      '**/node_modules/**',
      '**/generated/**',
      '**/playwright-report/**',
      '**/test-results/**',
      // Generated by `next build`; its triple-slash references are not ours to style.
      'apps/web/next-env.d.ts',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    languageOptions: {
      globals: { ...globals.node, ...globals.es2023 },
      parserOptions: { ecmaVersion: 2023, sourceType: 'module' },
    },
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],
      '@typescript-eslint/no-explicit-any': 'error',
      'no-console': ['error', { allow: ['warn', 'error'] }],
      eqeqeq: ['error', 'smart'],
      'prefer-const': 'error',
    },
  },
  {
    // The browser half of the workspace.
    files: ['apps/web/**/*.{ts,tsx}'],
    languageOptions: {
      globals: { ...globals.browser },
      parserOptions: { ecmaFeatures: { jsx: true } },
    },
    settings: { next: { rootDir: 'apps/web' } },
    plugins: { '@next/next': nextPlugin, 'react-hooks': reactHooks },
    rules: {
      ...nextPlugin.configs.recommended.rules,
      ...nextPlugin.configs['core-web-vitals'].rules,
      ...reactHooks.configs.recommended.rules,
      // App Router only; there is no `pages` directory for this rule to check against.
      '@next/next/no-html-link-for-pages': 'off',
    },
  },
  {
    // Nest reads decorator metadata at runtime; empty interfaces and parameter properties are
    // idiomatic there rather than accidents.
    files: ['apps/api/**/*.ts'],
    rules: {
      '@typescript-eslint/no-extraneous-class': 'off',
      // Nest resolves constructor dependencies from `design:paramtypes`, which the compiler only
      // emits for value imports. A `type` specifier on an injected class erases it and the
      // container fails to boot, so this rule is off where injection happens.
      '@typescript-eslint/consistent-type-imports': 'off',
    },
  },
  {
    // Command line entry points talk to the operator through stdout; that is their interface.
    files: ['**/prisma/seed.ts', '**/scripts/**/*.{ts,mjs}'],
    rules: { 'no-console': 'off' },
  },
  {
    files: ['**/test/**/*.ts', '**/tests/**/*.ts', '**/*.spec.ts', '**/*.config.{ts,mts,mjs}'],
    rules: { 'no-console': 'off', '@typescript-eslint/no-explicit-any': 'off' },
  },
);
